from typing import List

import numpy as np
import mne

from tms_eeg.io.writer import Writer
from tms_eeg.config.settings import ProjectConfig


class EpochAnnotationExporter:
    """Helper class for handling epoch annotations and exporting to ``.mat``.

    The class is deliberately lightweight – it stores the project configuration
    and pre‑computes a lower‑cased, whitespace‑free mapping from annotation names
    to the integer symbols defined in ``config.events.name_to_symbol``.  The public
    methods provide a clear, testable API:

    * :meth:`extract_annotations` – returns the epoch indexes and a list of
      annotation strings for a given ``mne.Epochs`` object.
    * :meth:`map_annotations_to_symbols` – converts the annotation strings to a
      NumPy array of symbols using the same case‑insensitive, space‑agnostic
      logic that the original script used.
    * :meth:`export_to_mat` – a thin wrapper around ``Writer.save_epochs_to_mat``
      that forwards the epochs and the computed symbol sequence.
    """

    def __init__(self, config: ProjectConfig):
        self.config = config
        # Normalise the name‑to‑symbol map once for fast look‑ups.
        self._symbol_map_lower = {
            k.lower().replace(" ", ""): v for k, v in self.config.events.name_to_symbol.items()
        }

    # ---------------------------------------------------------------------
    # Annotation extraction
    # ---------------------------------------------------------------------
    def extract_annotations(self, epochs: mne.Epochs) -> List[str]:
        """Extract the annotation strings corresponding to each epoch.

        Parameters
        ----------
        epochs : mne.Epochs
            The epochs from which to pull the annotation labels.

        Returns
        -------
        List[str]
            One human‑readable annotation name per epoch (in epoch order),
            derived from ``epochs.event_id`` and ``epochs.events``.
        """
        # Reverse the event_id mapping: {event_code: label}
        rev_id = {v: k for k, v in epochs.event_id.items()}
        return [rev_id[code] for code in epochs.events[:, 2]]

    # ---------------------------------------------------------------------
    # Symbol mapping
    # ---------------------------------------------------------------------
    def map_annotations_to_symbols(self, annotations: List[str]) -> np.ndarray:
        """Map a list of annotation strings to Context‑Tree symbols.

        The mapping mirrors the original script: annotation names are lower‑cased
        and spaces are removed before looking up the integer symbol in the
        configuration's ``events.name_to_symbol`` dictionary.
        """
        symbols = [
            self._symbol_map_lower[ann.lower().replace(" ", "")]
            for ann in annotations
        ]
        return np.array(symbols, dtype=int)

    # ---------------------------------------------------------------------
    # Export helper
    # ---------------------------------------------------------------------
    def export_to_mat(
        self,
        writer: Writer,
        epochs: mne.Epochs,
        symbols: np.ndarray,
        subfolder: str = "processed",
    ) -> None:
        """Save ``epochs`` to a MATLAB ``.mat`` file using ``Writer``.

        Parameters
        ----------
        writer : Writer
            Instance of the existing ``Writer`` class.
        epochs : mne.Epochs
            EEG epochs to be saved.
        symbols : np.ndarray
            Symbol sequence generated by :meth:`map_annotations_to_symbols`.
        subfolder : str, optional
            Destination subfolder inside the processed directory (default
            ``"processed"``).
        """
        writer.save_epochs_to_mat(epochs, symbol_sequence=symbols, subfolder=subfolder)
